schema: 1
base:
  name: mydistro
  version: "1.0"
  hostname: mydistro
  arch: x86_64
kernel:
  version: "6.12"
  preset: desktop
  features:
    - modules
    - apparmor
  config:
    HZ_1000: y
boot:
  loader: grub
  firmware: uefi
init:
  system: systemd
userland:
  libc: glibc
  coreutils: gnu
  shell: bash
packages:
  manager: apt
  browser: firefox
  terminal: alacritty
  editor: nano
  extra: []
desktop:
  environment: xfce
  display: x11
  login: lightdm
image:
  installer: live-iso
